name: 'Reusable Citrix Mgmt Drift Detection'

on:
  workflow_dispatch: 
  schedule:
    - cron: '41 3 * * *' # runs nightly at 3:41 am

jobs:
  call-reusable-drift-check:
    uses: ./.github/workflows/reusable-drift-check.yml
    with:
        TF_WORKSPACE: citrix-mgmt
        TF_DIR: citrix-mgmt
        TF_PROJECT_TITLE: "Reusable Citrix Mgmt"
    secrets: inherit
