on:
  workflow_dispatch: 
  # schedule:
  #   - cron: '41 3 * * *' # runs nightly at 3:41 am

name: 'Citrix Mgmt VMs Drift Detection'

jobs:
  call-reusable-drift-check:
    uses: ./.github/workflows/reusable-drift-check.yml
    with:
        TF_WORKSPACE: citrix-mgmt-vms
        TF_DIR: citrix-mgmt-vms
        TF_PROJECT_TITLE: "Citrix Mgmt VMs"
    secrets: inherit
