on:
  workflow_dispatch:
  push:
    branches:
      - '**'
      - '!main'
    paths: 
      - citrix-mgmt-vms/**
      
name: Citrix Mgmt VMs Feature Branches TF Plan On Pull or Push

jobs:
  call-reusable-tf-plan:
    uses: ./.github/workflows/reusable-tf-plan.yml
    with:
        TF_WORKSPACE: citrix-mgmt-vms
        TF_DIR: citrix-mgmt-vms
    secrets: inherit
