
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths: 
      - citrix-mgmt/**
  pull_request:
    branches:
      - main
    paths: 
      - citrix-mgmt/**
      
name: Reusable Citrix Mgmt Main Branch TF Apply On Pull or Push

jobs:
  call-reusable-tf-plan:
    uses: ./.github/workflows/reusable-tf-plan.yml
    with:
        TF_WORKSPACE: citrix-mgmt
        TF_DIR: citrix-mgmt
    secrets: inherit

  call-reusable-tf_apply:
    uses: ./.github/workflows/reusable-tf-apply.yml
    needs: call-reusable-tf-plan
    with:
        TF_WORKSPACE: citrix-mgmt
        TF_DIR: citrix-mgmt
        TF_PLAN_SHA: ${{ needs.call-reusable-tf-plan.outputs.TF_PLAN_SHA }}
        TF_PLAN_EXIT_CODE: ${{ needs.call-reusable-tf-plan.outputs.TF_PLAN_EXIT_CODE }}
    secrets: inherit