on:
  workflow_dispatch: 
  # schedule:
  #   - cron: '41 3 * * *' # runs nightly at 3:41 am

name: 'Epic Mgmt Drift Detection'

jobs:
  call-reusable-drift-check:
    uses: ./.github/workflows/reusable-drift-check.yml
    with:
        TF_WORKSPACE: epic-mgmt
        TF_DIR: epic-mgmt
        TF_PROJECT_TITLE: "Epic Mgmt"
    secrets: inherit
