on:
  workflow_dispatch:
  push:
    branches:
      - '!main'
    paths: 
      - epic-mgmt/**
      
name: Epic Mgmt Feature Branches Terraform Plan On Pull or Push

jobs:
  call-reusable-tf-plan:
    uses: ./.github/workflows/reusable-tf-plan.yml
    with:
        TF_WORKSPACE: epic-mgmt
        TF_DIR: epic-mgmt
    secrets: inherit
