on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths: 
      - presentation-eus2/**
  pull_request:
    branches:
      - main
    paths: 
      - presentation-eus2/**
      
name: Presentation East US 2 Main Branch TF Apply On Pull or Push

jobs:
  call-reusable-tf-plan:
    uses: ./.github/workflows/reusable-tf-plan.yml
    with:
        TF_WORKSPACE: presentation-eus2
        TF_DIR: presentation-eus2
    secrets: inherit

  call-reusable-tf-apply:
    uses: ./.github/workflows/reusable-tf-apply.yml
    needs: call-reusable-tf-plan
    with:
        TF_WORKSPACE: presentation-eus2
        TF_DIR: presentation-eus2
        TF_PLAN_SHA: ${{ needs.call-reusable-tf-plan.outputs.TF_PLAN_SHA }}
        TF_PLAN_EXIT_CODE: ${{ needs.call-reusable-tf-plan.outputs.TF_PLAN_EXIT_CODE }}
    secrets: inherit
