on:
  workflow_dispatch:
  push:
    branches:
      - '!main'
    paths: 
      - presentation-cus/**
      
name: Presentation Central US Feature Branches Terraform Plan On Pull or Push

jobs:
  call-reusable-tf-plan:
    uses: ./.github/workflows/reusable-tf-plan.yml
    with:
        TF_WORKSPACE: presentation-cus
        TF_DIR: presentation-cus
    secrets: inherit