on:
  workflow_dispatch: 
  # schedule:
  #   - cron: '41 3 * * *' # runs nightly at 3:41 am

name: 'Presentation Central US Drift Detection'

jobs:
  call-reusable-drift-check:
    uses: ./.github/workflows/reusable-drift-check.yml
    with:
        TF_WORKSPACE: presentation-cus
        TF_DIR: presentation-cus
        TF_PROJECT_TITLE: "Presentation Central US"
    secrets: inherit
