on:
  workflow_dispatch:
  push:
    branches:
      - '!main'
    paths: 
      - presentation-eus2/**
  pull_request:
    branches:
      - '!main'
    paths: 
      - presentation-eus2/**

name: Presentation East US 2 Feature Branches Terraform Plan On Pull or Push

jobs:
  call-reusable-tf-plan:
    uses: ./.github/workflows/reusable-tf-plan.yml
    with:
        TF_WORKSPACE: presentation-eus2
        TF_DIR: presentation-eus2
    secrets: inherit
