on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths: 
      - vms-bld-cus/**
  pull_request:
    branches:
      - main
    paths: 
      - vms-bld-cus/**
      
name: VMs BLD CUS Main Branch TF Apply On Pull or Push

jobs:
  call-reusable-tf-plan:
    uses: ./.github/workflows/reusable-tf-plan.yml
    with:
        TF_WORKSPACE: vms-bld-cus
        TF_DIR: vms/bld/cus
    secrets: inherit

  call-reusable-tf-apply:
    uses: ./.github/workflows/reusable-tf-apply.yml
    needs: call-reusable-tf-plan
    with:
        TF_WORKSPACE: vms-bld-cus
        TF_DIR: vms/bld/cus
        TF_PLAN_SHA: ${{ needs.call-reusable-tf-plan.outputs.TF_PLAN_SHA }}
        TF_PLAN_EXIT_CODE: ${{ needs.call-reusable-tf-plan.outputs.TF_PLAN_EXIT_CODE }}
    secrets: inherit
