on:
  workflow_dispatch:
  push:
    branches:
      - '**'
      - '!main'
    paths: 
      - vms-prd-eus2/**
      
name: VMs PRD EUS2 Feature Branches TF Plan On Pull or Push

jobs:
  call-reusable-tf-plan:
    uses: ./.github/workflows/reusable-tf-plan.yml
    with:
        TF_WORKSPACE: vms-prd-eus2
        TF_DIR: vms/prd/eus2
    secrets: inherit
