on:
  workflow_dispatch:
  push:
    branches:
      - '!main'
    paths: 
      - vms-prd-cus/**
  pull_request:
    branches:
      - '!main'
    paths: 
      - vms-prd-cus/**

name: VMs PRD CUS Feature Branches TF Plan On Pull or Push

jobs:
  call-reusable-tf-plan:
    uses: ./.github/workflows/reusable-tf-plan.yml
    with:
        TF_WORKSPACE: vms-prd-cus
        TF_DIR: vms/prd/cus
    secrets: inherit
