on:
  workflow_dispatch: 
  schedule:
    - cron: '41 3 * * *' # runs nightly at 3:41 am

name: 'VMs BLD East US 2 Drift Detection'

jobs:
  call-reusable-drift-check:
    uses: ./.github/workflows/reusable-drift-check.yml
    with:
        TF_WORKSPACE: vms-bld-eus2
        TF_DIR: vms/bld/eus2
        TF_PROJECT_TITLE: "VMs BLD East US 2"
    secrets: inherit
