on:
  workflow_dispatch:
  push:
    branches:
      - '!main'
    paths: 
      - vms-bld-eus2/**
  pull_request:
    branches:
      - '!main'
    paths: 
      - vms-bld-eus2/**

name: VMs BLD EUS2 Feature Branches TF Plan On Pull or Push

jobs:
  call-reusable-tf-plan:
    uses: ./.github/workflows/reusable-tf-plan.yml
    with:
        TF_WORKSPACE: vms-bld-eus2
        TF_DIR: vms/bld/eus2
    secrets: inherit
