on:
  workflow_dispatch: 
  schedule:
    - cron: '41 3 * * *' # runs nightly at 3:41 am

name: 'VMs BLD Central US Drift Detection'

jobs:
  call-reusable-drift-check:
    uses: ./.github/workflows/reusable-drift-check.yml
    with:
        TF_WORKSPACE: vms-bld-cus
        TF_DIR: vms/bld/cus
        TF_PROJECT_TITLE: "VMs BLD Central US"
    secrets: inherit
