on:
  workflow_dispatch: 
  schedule:
    - cron: '41 3 * * *' # runs nightly at 3:41 am

name: 'VMs PRD East US 2 Drift Detection'

jobs:
  call-reusable-drift-check:
    uses: ./.github/workflows/reusable-drift-check.yml
    with:
        TF_WORKSPACE: vms-prd-cus
        TF_DIR: vms/prd/cus
        TF_PROJECT_TITLE: "VMs PRD East US 2"
    secrets: inherit
